project:
  type: website
  output-dir: docs
website:
  title: "alex-nguyen-vn.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Alex-Nguyen-VN
      - icon: linkedin
        href: https://www.linkedin.com/in/nguyen-thanh-cuong-20849552/
format:
  html:
    theme: cosmo
    css: styles.css



